spring:  application:    name: 'ponto'  activemq:    broker-url: tcp://localhost:61616    user: admin    password: admin

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: http://localhost:8761/eureka            