
server:  port: 8888
  


spring:
  cloud:
     config:
       server:
        git:
          uri: http://src.farol.com.br/raphael.fernandes/microservice-repo
          search-paths: colaboradores, pontos
          

        